# TODO-02: Set the spring.application.name to "Lab05 Images" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set the model-specific attributes according to the lab instructions.
# Take advantage of YAML's hierarchical structure to set these values.
spring:
  application.name: Lab05 Images
  main.web-application-type: none     # Do not start a web server.

ai:
  retry:
    max-attempts: 1           # Maximum number of retry attempts.
  openai:
    image:
      enabled: true
      options:
        n: 1                  # number of images to generate.
        response_format: url  # or b64_json
        size: 1024x1024       # or 1024x1024, 1024x1792
        style: vivid        # or natural, stylized, artstation, pixel_art, hd
